version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
environment:
  PYTHON: C:\Python37-x64
build_script:
- ps: .\make.bat prod
test_script:
- ps: .\make.bat test